# Generated by Django 2.2.4 on 2019-09-13 07:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('paterno', models.CharField(max_length=50)),
                ('materno', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id_diploma', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('tipo_fuente', models.CharField(max_length=150)),
                ('estilo_fuente', models.CharField(max_length=150)),
                ('coordenada_x', models.BigIntegerField()),
                ('coordenada_y', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=270)),
                ('tipo', models.CharField(choices=[('SINGLE', 'Single'), ('MULTIPLE', 'Multiple')], default='SINGLE', max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='grupo',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta_Opcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Opcion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Pregunta')),
            ],
            options={
                'db_table': 'pregunta_opcion',
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='opciones',
            field=models.ManyToManyField(through='dashboard.Pregunta_Opcion', to='dashboard.Opcion'),
        ),
        migrations.CreateModel(
            name='Grupo_Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.BigIntegerField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Grupo')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Pregunta')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Opcion')),
            ],
            options={
                'db_table': 'grupo_pregunta',
            },
        ),
        migrations.CreateModel(
            name='Grupo_Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encuestado', models.BooleanField(default=False)),
                ('calificacion_numero', models.DecimalField(decimal_places=1, max_digits=3)),
                ('calificacion_letra', models.CharField(max_length=100)),
                ('diploma_habilitado', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Alumno')),
                ('diploma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Diploma')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Grupo')),
            ],
            options={
                'db_table': 'grupo_alumno',
            },
        ),
        migrations.CreateModel(
            name='Alumno_Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField()),
                ('hora_entrega', models.TimeField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Actividad')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Alumno')),
            ],
            options={
                'db_table': 'alumno_actividad',
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='actividades',
            field=models.ManyToManyField(through='dashboard.Alumno_Actividad', to='dashboard.Actividad'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sesion'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='alumnos',
            field=models.ManyToManyField(through='dashboard.Grupo_Alumno', to='dashboard.Alumno'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='resumen_preguntas',
            field=models.ManyToManyField(through='dashboard.Grupo_Pregunta', to='dashboard.Pregunta'),
        ),
    ]
