# Generated by Django 2.2.4 on 2019-09-13 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190913_0257'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='grupo_alumno',
            table='dashboard_grupo_alumno',
        ),
        migrations.AlterModelTable(
            name='grupo_pregunta',
            table='dashboard_grupo_pregunta',
        ),
        migrations.AlterModelTable(
            name='pregunta_opcion',
            table='dashboard_pregunta_opcion',
        ),
    ]
