# Generated by Django 2.2.4 on 2019-09-13 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190913_0310'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alumno_actividad',
            table='dashboard_alumno_actividad',
        ),
    ]
