# Generated by Django 2.2.4 on 2019-09-18 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190913_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo_alumno',
            name='diploma',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Diploma'),
        ),
    ]
