# Generated by Django 2.2.4 on 2019-09-18 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20190918_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo_alumno',
            name='diploma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Diploma'),
        ),
    ]
